name: convertpage
description: con
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  micro_routes:
    path: ../../../micro_routes

  lottie: ^2.3.2
  equatable:
  http: ^0.13.5
  flutter_bloc: ^8.1.2
  qlevar_router:
  flutter_svg: ^2.0.5
  flutter_platform_widgets: ^3.3.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator:
  path_provider: ^2.0.15
  responsive_builder: ^0.7.0
  flutter_bootstrap: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
